"use client";

import { FormEvent, useEffect, useState } from "react";
import { useAuth } from "./auth-provider";
import { listConversations, listMessages, sendMessage } from "../lib/api";
import { ChatMessage, Conversation } from "../types";

export default function ChatWorkspace() {
  const { auth } = useAuth(); const [rooms, setRooms] = useState<Conversation[]>([]); const [selected, setSelected] = useState<number | null>(null); const [messages, setMessages] = useState<ChatMessage[]>([]); const [error, setError] = useState("");
  async function loadRooms() { if (!auth?.token) return; try { const data = await listConversations(auth.token); setRooms(data.items); const requested = Number(new URLSearchParams(window.location.search).get("room")); setSelected((current) => current || (data.items.some((item) => item.id === requested) ? requested : data.items[0]?.id ?? null)); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load conversations"); } }
  async function loadMessages(roomId: number) { if (!auth?.token) return; try { setMessages((await listMessages(auth.token, roomId)).items); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load messages"); } }
  useEffect(() => { loadRooms(); }, [auth?.token]);
  useEffect(() => { if (!selected) { setMessages([]); return; } loadMessages(selected); const timer = window.setInterval(() => loadMessages(selected), 5000); return () => window.clearInterval(timer); }, [selected, auth?.token]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!auth?.token || !selected) return; const form = event.currentTarget; const data = new FormData(form); const content = String(data.get("content") || "").trim(); if (!content) return; try { await sendMessage(auth.token, selected, content); form.reset(); await loadMessages(selected); await loadRooms(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to send the message"); } }
  const room = rooms.find((item) => item.id === selected);
  return <div className="grid min-h-[540px] overflow-hidden rounded-3xl bg-white shadow-xl md:grid-cols-[280px_1fr]">
    <aside className="border-r border-slate-200 bg-slate-50 p-3"><h2 className="px-3 py-2 font-black">Conversations</h2><div className="space-y-2">{rooms.map((item) => { const name = auth?.user.role === "EMPLOYER" ? item.candidate.fullName : item.employer.employerProfile?.companyName || item.employer.fullName; return <button key={item.id} onClick={() => setSelected(item.id)} className={`w-full rounded-2xl p-3 text-left ${selected === item.id ? "bg-blue-600 text-white" : "bg-white hover:bg-blue-50"}`}><p className="font-bold">{name}</p><p className="mt-1 truncate text-xs opacity-70">{item.messages[0]?.content || "Start a conversation"}</p></button>; })}</div>{!rooms.length ? <p className="p-3 text-sm text-slate-500">No conversations yet. Candidates can start one from the job search page.</p> : null}</aside>
    <section className="flex min-h-[540px] flex-col"><div className="border-b p-4"><h2 className="font-black">{room ? (auth?.user.role === "EMPLOYER" ? room.candidate.fullName : room.employer.employerProfile?.companyName || room.employer.fullName) : "Select a conversation"}</h2><p className="text-xs text-emerald-600">● Basic chat · refreshes every 5 seconds</p></div><div className="flex-1 space-y-3 overflow-y-auto p-5">{messages.map((item) => { const mine = item.senderId === auth?.user.id; return <div key={item.id} className={`flex ${mine ? "justify-end" : "justify-start"}`}><div className={`max-w-[75%] rounded-2xl px-4 py-3 ${mine ? "bg-blue-600 text-white" : "bg-slate-100 text-slate-800"}`}><p className="text-sm">{item.content}</p><p className="mt-1 text-[10px] opacity-60">{new Date(item.createdAt).toLocaleString("en-US")}</p></div></div>; })}</div><form onSubmit={submit} className="flex gap-2 border-t p-4"><input name="content" disabled={!selected} autoComplete="off" placeholder="Type a message..." className="flex-1 rounded-xl border p-3"/><button disabled={!selected} className="rounded-xl bg-blue-600 px-5 font-bold text-white disabled:opacity-40">Send</button></form>{error ? <p className="px-4 pb-3 text-sm text-rose-600">{error}</p> : null}</section>
  </div>;
}
